//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.04 at 06:15:56 PM PST 
//


package org.netbeams.dsp.demo.mouseactions;

import org.netbeams.dsp.message.XmlDecoratable;


/**
 * <p>Java class for buttonName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="buttonName">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="RIGHT"/>
 *     &lt;enumeration value="LEFT"/>
 *     &lt;enumeration value="CENTER"/>
 *     &lt;enumeration value="NONE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
//@XmlType(name = "buttonName")
//@XmlEnum
public enum ButtonName implements XmlDecoratable {

    RIGHT,
    LEFT,
    CENTER,
    NONE;

    public String value() {
        return name();
    }

    public static ButtonName fromValue(String v) {
        return valueOf(v);
    }

    public String toXml() {
        return " button=\"" + this + "\"";
    }    
}
