//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.04 at 06:15:49 PM PST 
//


package org.netbeams.dsp.data.property;

import java.util.ArrayList;
import java.util.List;

import org.netbeams.dsp.message.MessageContent;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netbeams.dsp.org/message.xsd}AbstractMessageContent">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="Property" type="{http://www.netbeams.dsp.org/dsproperty.xsd}DSProperty"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class DSProperties
    extends MessageContent
{

//    @XmlElement(name = "Property", required = true)
    protected List<DSProperty> property;

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DSProperty }
     * 
     * 
     */
    public List<DSProperty> getProperty() {
        if (property == null) {
            property = new ArrayList<DSProperty>();
        }
        return this.property;
    }

    public String toXml() {
        StringBuilder builder = new StringBuilder();
        builder.append("<DSProperties>");
        for(DSProperty property : this.property) {
            builder.append(property.toXml());
        }
        builder.append("</DSProperties>");
        return builder.toString();
    }
}
