//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.04 at 06:15:56 PM PST 
//


package org.netbeams.dsp.demo.mouseactions;

import org.netbeams.dsp.message.XmlDecoratable;


/**
 * <p>Java class for eventName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="eventName">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CLICKED"/>
 *     &lt;enumeration value="RELEASED"/>
 *     &lt;enumeration value="DRAGGED"/>
 *     &lt;enumeration value="ENTERED"/>
 *     &lt;enumeration value="EXITED"/>
 *     &lt;enumeration value="MOVED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
//@XmlType(name = "eventName")
//@XmlEnum
public enum EventName implements XmlDecoratable {

    CLICKED,
    RELEASED,
    DRAGGED,
    ENTERED,
    EXITED,
    MOVED;

    public String value() {
        return name();
    }

    public static EventName fromValue(String v) {
        return valueOf(v);
    }

    public String toXml() {
        return " event=\"" + this + "\"";
    }

}
