//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.04 at 06:15:56 PM PST 
//


package org.netbeams.dsp.demo.mouseactions;


import java.util.ArrayList;
import java.util.List;

import org.netbeams.dsp.message.MessageContent;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netbeams.dsp.org/message.xsd}AbstractMessageContent">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="mouseAction" type="{http://dsp.netbeams.org/demo/mouseaction.xsd}mouseAction"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "", propOrder = {
//    "mouseAction"
//})
//@XmlRootElement(name = "mouseActionsContainer")
public class MouseActionsContainer
    extends MessageContent
{

    //@XmlElement(required = true)
    protected List<MouseAction> mouseAction;

    /**
     * Gets the value of the mouseAction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mouseAction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMouseAction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MouseAction }
     * 
     * 
     */
    public List<MouseAction> getMouseAction() {
        if (mouseAction == null) {
            mouseAction = new ArrayList<MouseAction>();
        }
        return this.mouseAction;
    }

    public String toXml() {
        StringBuilder builder = new StringBuilder();

        builder.append("<mouseaction:mouseActionsContainer " +
        		"xmlns:mouseaction=\"http://dsp.netbeams.org/demo/mouseaction.xsd\">");
        for(MouseAction mac : this.mouseAction) {
            builder.append(mac.toXml());
        }
        builder.append("</mouseaction:mouseActionsContainer>");
        return builder.toString();        
    }

    public static void main(String[] args) {
        MouseActionsContainer acc = new MouseActionsContainer();
        MouseAction a = new MouseAction();
        a.setButton(ButtonName.CENTER);
        a.setEvent(EventName.DRAGGED);
        a.setX(3);
        a.setY(55);
        acc.getMouseAction().add(a);
        
        System.out.println(acc.toXml());
    }
}
