//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.25 at 11:43:48 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.netbeams.dsp.org/stocktick.xsd")
package org.netbeams.dsp.demo.stock;
