//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.18 at 10:37:17 PM PDT 
//


package org.netbeams.dsp.demo.stock;

import java.util.ArrayList;
import java.util.List;
import org.netbeams.dsp.message.MessageContent;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netbeams.dsp.org/message.xsd}AbstractMessageContent">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="StockTick" type="{http://www.netbeams.dsp.org/stocktick.xsd}StockTick"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class StockTicks
    extends MessageContent
{

    //@XmlElement(name = "StockTick", required = true)
    protected List<StockTick> stockTick;

    /**
     * Gets the value of the stockTick property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stockTick property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStockTick().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StockTick }
     * 
     * 
     */
    public List<StockTick> getStockTick() {
        if (stockTick == null) {
            stockTick = new ArrayList<StockTick>();
        }
        return this.stockTick;
    }
    
    public String toXml() {
        StringBuilder builder = new StringBuilder();
        builder.append("<StockTicks>");
        for(StockTick data : this.stockTick) {
            builder.append(data.toXml());
        }
        builder.append("</StockTicks>");
        return builder.toString();
    }

}
