//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.03 at 10:30:56 AM PDT 
//


package edu.sfsu.netbeams.web.dmpstate;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PluginType" type="{}PluginType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PlugInstance" type="{}PluginInstance" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pluginTypes",
    "plugInstances"
})
@XmlRootElement(name = "DMPState")
public class DMPState {

    @XmlElement(name = "PluginType")
    protected List<PluginType> pluginTypes;
    @XmlElement(name = "PlugInstance")
    protected List<PluginInstance> plugInstances;

    /**
     * Gets the value of the pluginTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pluginTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPluginTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PluginType }
     * 
     * 
     */
    public List<PluginType> getPluginTypes() {
        if (pluginTypes == null) {
            pluginTypes = new ArrayList<PluginType>();
        }
        return this.pluginTypes;
    }

    /**
     * Gets the value of the plugInstances property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the plugInstances property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlugInstances().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PluginInstance }
     * 
     * 
     */
    public List<PluginInstance> getPlugInstances() {
        if (plugInstances == null) {
            plugInstances = new ArrayList<PluginInstance>();
        }
        return this.plugInstances;
    }

}
