//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.30 at 12:01:21 PM PST 
//


package org.netbeams.dsp.message;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.netbeams.dsp.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.netbeams.dsp.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MeasureMessage }
     * 
     */
    public MeasureMessage createMeasureMessage() {
        return new MeasureMessage();
    }

    /**
     * Create an instance of {@link CreateMessage }
     * 
     */
    public CreateMessage createCreateMessage() {
        return new CreateMessage();
    }

    /**
     * Create an instance of {@link QueryMessage }
     * 
     */
    public QueryMessage createQueryMessage() {
        return new QueryMessage();
    }

    /**
     * Create an instance of {@link AbstractNodeAddress }
     * 
     */
    public AbstractNodeAddress createAbstractNodeAddress() {
        return new NodeAddress();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link DeleteMessage }
     * 
     */
    public DeleteMessage createDeleteMessage() {
        return new DeleteMessage();
    }

    /**
     * Create an instance of {@link UpdateMessage }
     * 
     */
    public UpdateMessage createUpdateMessage() {
        return new UpdateMessage();
    }

    /**
     * Create an instance of {@link ComponentIdentifier }
     * 
     */
    public ComponentIdentifier createComponentIdentifier() {
        return new ComponentIdentifier();
    }

    /**
     * Create an instance of {@link ActionMessage }
     * 
     */
    public ActionMessage createActionMessage() {
        return new ActionMessage();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link InsertMessage }
     * 
     */
    public InsertMessage createInsertMessage() {
        return new InsertMessage();
    }

    /**
     * Create an instance of {@link EventMessage }
     * 
     */
    public EventMessage createEventMessage() {
        return new EventMessage();
    }

    /**
     * Create an instance of {@link AbstractMessage }
     * 
     */
    public AbstractMessage createAbstractMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link ComponentLocator }
     * 
     */
    public ComponentLocator createComponentLocator() {
        return new ComponentLocator();
    }

}
