//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.18 at 02:09:18 AM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.netbeams.dsp.org/message.xsd")
package org.netbeams.dsp.message;
