//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.22 at 08:53:00 PM PST 
//


package org.netbeams.dsp.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComponentLocator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComponentLocator">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NodeRefID" type="{http://www.netbeams.dsp.org/message.xsd}NodeRefID"/>
 *         &lt;element name="NodeAddress" type="{http://www.netbeams.dsp.org/message.xsd}NodeAddress"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComponentLocator", propOrder = {
    "nodeRefID",
    "nodeAddress"
})
public class ComponentLocator {

    @XmlElement(name = "NodeRefID", required = true)
    protected NodeRefID nodeRefID;
    @XmlElement(name = "NodeAddress", required = true)
    protected NodeAddress nodeAddress;

    /**
     * Gets the value of the nodeRefID property.
     * 
     * @return
     *     possible object is
     *     {@link NodeRefID }
     *     
     */
    public NodeRefID getNodeRefID() {
        return nodeRefID;
    }

    /**
     * Sets the value of the nodeRefID property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeRefID }
     *     
     */
    public void setNodeRefID(NodeRefID value) {
        this.nodeRefID = value;
    }

    /**
     * Gets the value of the nodeAddress property.
     * 
     * @return
     *     possible object is
     *     {@link NodeAddress }
     *     
     */
    public NodeAddress getNodeAddress() {
        return nodeAddress;
    }

    /**
     * Sets the value of the nodeAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeAddress }
     *     
     */
    public void setNodeAddress(NodeAddress value) {
        this.nodeAddress = value;
    }

}
