//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.22 at 08:53:00 PM PST 
//


package org.netbeams.dsp.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Message complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Message">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://www.netbeams.dsp.org/message.xsd}Header"/>
 *         &lt;element name="BodyContainer" type="{http://www.netbeams.dsp.org/message.xsd}BodyContainer"/>
 *       &lt;/sequence>
 *       &lt;attribute name="messageID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Message", propOrder = {
    "header",
    "bodyContainer"
})
public class Message {

    @XmlElement(name = "Header", required = true)
    protected Header header;
    @XmlElement(name = "BodyContainer", required = true)
    protected BodyContainer bodyContainer;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String messageID;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the bodyContainer property.
     * 
     * @return
     *     possible object is
     *     {@link BodyContainer }
     *     
     */
    public BodyContainer getBodyContainer() {
        return bodyContainer;
    }

    /**
     * Sets the value of the bodyContainer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyContainer }
     *     
     */
    public void setBodyContainer(BodyContainer value) {
        this.bodyContainer = value;
    }

    /**
     * Gets the value of the messageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageID() {
        return messageID;
    }

    /**
     * Sets the value of the messageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageID(String value) {
        this.messageID = value;
    }

}
