//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.23 at 11:55:37 PM PST 
//


package org.netbeams.dsp.message;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.netbeams.dsp.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MeasureMessage_QNAME = new QName("http://www.netbeams.dsp.org/message.xsd", "MeasureMessage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.netbeams.dsp.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComponentIdentifier }
     * 
     */
    public ComponentIdentifier createComponentIdentifier() {
        return new ComponentIdentifier();
    }

    /**
     * Create an instance of {@link MeasureMessage }
     * 
     */
    public MeasureMessage createMeasureMessage() {
        return new MeasureMessage();
    }

    /**
     * Create an instance of {@link ComponentType }
     * 
     */
    public ComponentType createComponentType() {
        return new ComponentType();
    }

    /**
     * Create an instance of {@link ComponentLocator }
     * 
     */
    public ComponentLocator createComponentLocator() {
        return new ComponentLocator();
    }

    /**
     * Create an instance of {@link LocalNodeAddress }
     * 
     */
    public LocalNodeAddress createLocalNodeAddress() {
        return new LocalNodeAddress();
    }

    /**
     * Create an instance of {@link NodeAddress }
     * 
     */
    public NodeAddress createNodeAddress() {
        return new NodeAddress();
    }

    /**
     * Create an instance of {@link NodeRefID }
     * 
     */
    public NodeRefID createNodeRefID() {
        return new NodeRefID();
    }

    /**
     * Create an instance of {@link AbstractMessage }
     * 
     */
    public AbstractMessage createAbstractMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MeasureMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.netbeams.dsp.org/message.xsd", name = "MeasureMessage")
    public JAXBElement<MeasureMessage> createMeasureMessage(MeasureMessage value) {
        return new JAXBElement<MeasureMessage>(_MeasureMessage_QNAME, MeasureMessage.class, null, value);
    }

}
