//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.22 at 08:53:00 PM PST 
//


package org.netbeams.dsp.message;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.netbeams.dsp.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EventMessage_QNAME = new QName("http://www.netbeams.dsp.org/message.xsd", "EventMessage");
    private final static QName _ActionMessage_QNAME = new QName("http://www.netbeams.dsp.org/message.xsd", "ActionMessage");
    private final static QName _UpdateMessage_QNAME = new QName("http://www.netbeams.dsp.org/message.xsd", "UpdateMessage");
    private final static QName _CreateMessage_QNAME = new QName("http://www.netbeams.dsp.org/message.xsd", "CreateMessage");
    private final static QName _QueryMessage_QNAME = new QName("http://www.netbeams.dsp.org/message.xsd", "QueryMessage");
    private final static QName _MeasureMessage_QNAME = new QName("http://www.netbeams.dsp.org/message.xsd", "MeasureMessage");
    private final static QName _InsertMessage_QNAME = new QName("http://www.netbeams.dsp.org/message.xsd", "InsertMessage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.netbeams.dsp.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComponentLocator }
     * 
     */
    public ComponentLocator createComponentLocator() {
        return new ComponentLocator();
    }

    /**
     * Create an instance of {@link LocalNodeAddress }
     * 
     */
    public LocalNodeAddress createLocalNodeAddress() {
        return new LocalNodeAddress();
    }

    /**
     * Create an instance of {@link NodeRefID }
     * 
     */
    public NodeRefID createNodeRefID() {
        return new NodeRefID();
    }

    /**
     * Create an instance of {@link ComponentType }
     * 
     */
    public ComponentType createComponentType() {
        return new ComponentType();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link ComponentIdentifier }
     * 
     */
    public ComponentIdentifier createComponentIdentifier() {
        return new ComponentIdentifier();
    }

    /**
     * Create an instance of {@link BodyContainer }
     * 
     */
    public BodyContainer createBodyContainer() {
        return new BodyContainer();
    }

    /**
     * Create an instance of {@link NodeAddress }
     * 
     */
    public NodeAddress createNodeAddress() {
        return new NodeAddress();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Message }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.netbeams.dsp.org/message.xsd", name = "EventMessage")
    public JAXBElement<Message> createEventMessage(Message value) {
        return new JAXBElement<Message>(_EventMessage_QNAME, Message.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Message }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.netbeams.dsp.org/message.xsd", name = "ActionMessage")
    public JAXBElement<Message> createActionMessage(Message value) {
        return new JAXBElement<Message>(_ActionMessage_QNAME, Message.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Message }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.netbeams.dsp.org/message.xsd", name = "UpdateMessage")
    public JAXBElement<Message> createUpdateMessage(Message value) {
        return new JAXBElement<Message>(_UpdateMessage_QNAME, Message.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Message }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.netbeams.dsp.org/message.xsd", name = "CreateMessage")
    public JAXBElement<Message> createCreateMessage(Message value) {
        return new JAXBElement<Message>(_CreateMessage_QNAME, Message.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Message }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.netbeams.dsp.org/message.xsd", name = "QueryMessage")
    public JAXBElement<Message> createQueryMessage(Message value) {
        return new JAXBElement<Message>(_QueryMessage_QNAME, Message.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Message }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.netbeams.dsp.org/message.xsd", name = "MeasureMessage")
    public JAXBElement<Message> createMeasureMessage(Message value) {
        return new JAXBElement<Message>(_MeasureMessage_QNAME, Message.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Message }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.netbeams.dsp.org/message.xsd", name = "InsertMessage")
    public JAXBElement<Message> createInsertMessage(Message value) {
        return new JAXBElement<Message>(_InsertMessage_QNAME, Message.class, null, value);
    }

}
