//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.30 at 04:40:55 AM PST 
//


package org.netbeams.dsp.message.content;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.netbeams.dsp.message.MessageContent;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netbeams.dsp.org/message.xsd}AbstractMessageContent">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="ack" type="{http://dsp.netbeams.org/acknowledgements.xsd}ackType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ack"
})
@XmlRootElement(name = "acksContainer")
public class AcksContainer
    extends MessageContent
{

    @XmlElement(required = true)
    protected List<AckType> ack;

    /**
     * Gets the value of the ack property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ack property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAck().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AckType }
     * 
     * 
     */
    public List<AckType> getAck() {
        if (ack == null) {
            ack = new ArrayList<AckType>();
        }
        return this.ack;
    }

}
