//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.30 at 04:40:55 AM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dsp.netbeams.org/acknowledgements.xsd")
package org.netbeams.dsp.message.content;
