//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.04 at 06:20:22 PM PST 
//


package org.netbeams.dsp.ysi;

/**
 * <p>Java class for sondeDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sondeDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Temp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SpCond" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cond" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Resist" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Sal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Press" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Depth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phmV" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ODOSat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ODOConc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Turbid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Battery" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class SondeDataType {

//    @XmlElement(name = "Date", required = true)
    protected String date;
//    @XmlElement(name = "Time", required = true)
    protected String time;
//    @XmlElement(name = "Temp", required = true)
    protected String temp;
//    @XmlElement(name = "SpCond", required = true)
    protected String spCond;
//    @XmlElement(name = "Cond", required = true)
    protected String cond;
//    @XmlElement(name = "Resist", required = true)
    protected String resist;
//    @XmlElement(name = "Sal", required = true)
    protected String sal;
//    @XmlElement(name = "Press", required = true)
    protected String press;
//    @XmlElement(name = "Depth", required = true)
    protected String depth;
//    @XmlElement(name = "pH", required = true)
    protected String ph;
//    @XmlElement(required = true)
    protected String phmV;
//    @XmlElement(name = "ODOSat", required = true)
    protected String odoSat;
//    @XmlElement(name = "ODOConc", required = true)
    protected String odoConc;
//    @XmlElement(name = "Turbid", required = true)
    protected String turbid;
//    @XmlElement(name = "Battery", required = true)
    protected String battery;

    public SondeDataType() {
        this.date = "";
        this.time = "";
        this.temp = "";
        this.spCond = "";
        this.cond = "";
        this.resist = "";
        this.sal = "";
        this.press = "";
        this.depth = ""; 
        this.ph = "";
        this.phmV = "";
        this.odoSat = "";
        this.odoConc = "";
        this.turbid = "";
        this.battery = "";
    }
    
    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime(String value) {
        this.time = value;
    }

    /**
     * Gets the value of the temp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemp() {
        return temp;
    }

    /**
     * Sets the value of the temp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemp(String value) {
        this.temp = value;
    }

    /**
     * Gets the value of the spCond property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpCond() {
        return spCond;
    }

    /**
     * Sets the value of the spCond property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpCond(String value) {
        this.spCond = value;
    }

    /**
     * Gets the value of the cond property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCond() {
        return cond;
    }

    /**
     * Sets the value of the cond property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCond(String value) {
        this.cond = value;
    }

    /**
     * Gets the value of the resist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResist() {
        return resist;
    }

    /**
     * Sets the value of the resist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResist(String value) {
        this.resist = value;
    }

    /**
     * Gets the value of the sal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSal() {
        return sal;
    }

    /**
     * Sets the value of the sal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSal(String value) {
        this.sal = value;
    }

    /**
     * Gets the value of the press property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPress() {
        return press;
    }

    /**
     * Sets the value of the press property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPress(String value) {
        this.press = value;
    }

    /**
     * Gets the value of the depth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepth() {
        return depth;
    }

    /**
     * Sets the value of the depth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepth(String value) {
        this.depth = value;
    }

    /**
     * Gets the value of the ph property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPH() {
        return ph;
    }

    /**
     * Sets the value of the ph property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPH(String value) {
        this.ph = value;
    }

    /**
     * Gets the value of the phmV property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhmV() {
        return phmV;
    }

    /**
     * Sets the value of the phmV property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhmV(String value) {
        this.phmV = value;
    }

    /**
     * Gets the value of the odoSat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getODOSat() {
        return odoSat;
    }

    /**
     * Sets the value of the odoSat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setODOSat(String value) {
        this.odoSat = value;
    }

    /**
     * Gets the value of the odoConc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getODOConc() {
        return odoConc;
    }

    /**
     * Sets the value of the odoConc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setODOConc(String value) {
        this.odoConc = value;
    }

    /**
     * Gets the value of the turbid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTurbid() {
        return turbid;
    }

    /**
     * Sets the value of the turbid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTurbid(String value) {
        this.turbid = value;
    }

    /**
     * Gets the value of the battery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBattery() {
        return battery;
    }

    /**
     * Sets the value of the battery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBattery(String value) {
        this.battery = value;
    }

    public String toXml() {
        StringBuilder builder = new StringBuilder();
        builder.append("<soundeData ");
        if (this.date != null) {
            builder.append("date=\"" + this.date + "\" ");
        }
        if (this.time != null) {
            builder.append("time=\"" + this.time + "\"");
        }
        builder.append(">");
        builder.append("<SpCond>" + this.spCond + "</SpCond>");
        builder.append("<Cond>" + this.cond + "</Cond>");
        builder.append("<Resist>" + this.resist + "</Resist>");
        builder.append("<Sal>" + this.sal + "</Sal>");
        builder.append("<Press>" + this.press + "</Press>");
        builder.append("<Depth>" + this.depth + "</Depth>");
        builder.append("<pH>" + this.ph + "</pH>");
        builder.append("<phmV>" + this.phmV + "</phmV>");
        builder.append("<ODOSat>" + this.odoSat + "</ODOSat>");
        builder.append("<ODOConc>" + this.odoConc + "</ODOConc>");
        builder.append("<Turbid>" + this.turbid + "</Turbid>");
        builder.append("<Battery>" + this.battery + "</Battery>");
        builder.append("</soundeData>");
        return builder.toString();
    }

}
